### ISSUE TITLE
Tweak count_cells.py to consume multiple matrices per project

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#46]
Inputs are in `projects/$uuid/matrices/`.

Instead of counting the number of unique barcode indices in the `.mtx` file we may have to switch to merging the rows in each of the `barcodes.tsv.gz` file into a single set and then returning the size of that set. That takes care of overlap between the matrices but does not deal with orphaned row in the `barcodes.tsv.gz` file (rows that aren't referenced by an entry in the `.mtx` file).

**Comment by nadove-ucsc** [comment]
I spoke with Beth this morning and she said that overlap between barcodes (at least small overlap, ~1% of all barcodes per file) is probably due to errors/collisions/namespace exhaustion and not due to individual cells actually being present in multiple matrices. She recommended to ignore these collisions for the purpose of counting cells.

**Comment by hannes-ucsc** [comment]
Sounds good, let's do that. Simply count the unique barcode indices in each `.mtx` individually and return their sum.

**Comment by dsotirho-ucsc** [comment]
PR #59
