### ISSUE TITLE
DB shows 47 matrices while instance only stores 46

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#75]

**Comment by hannes-ucsc** [comment]
@danielsotirhos added a project (`GSE132566 -> df1875a9-1a6a-58e0-8fd2-dac0ebb3b1b2`) with per-cell matrices in one of his [PRs](https://github.com/DailyDreaming/load-project/pull/71/files#r364574662). I later [removed](https://github.com/DailyDreaming/load-project/commit/542e8232850cf405d1786c32823da1161ab7bf4c#diff-c3152a2e2df235a9c932de5ea37fb36bL1484) that project again because its matrix should be generated [differently](https://github.com/DailyDreaming/load-project/issues/43). For expediency, I then ran `make bundles` before `make clean_matrices` and `make matrices`. `make bundles` used the matrix created when Daniel tested his code. `make clean_matrices` removed it and `make matrices` did not generate it again, due to me removing the code.

**Comment by hannes-ucsc** [comment]
We need to reingest that bundle. The file should disappear.

**Comment by hannes-ucsc** [comment]
Reingesting the bundle did not remove the file. I think that because `analysis_file_0.json` is left in the `bundle` directory for that project even though there is no `matrix.mtx.zip` anymore. I thought we delete the json files before generating them. I think I spotted the mistake:

https://github.com/DailyDreaming/load-project/blob/f4bca9f7ddccf2592b3e7021f89207c56914caa2/create_project.py#L974

Shouldn't that read `args.clean` instead of `args.clear`?

@DailyDreaming

**Comment by DailyDreaming** [comment]
@hannes-ucsc Yes, though that line's never run, PR posted: https://github.com/DailyDreaming/load-project/pull/80

Just to record it here, we discussed this and determined it was most likely the order in which commands were run so that it's very likely that the matrix file still existed prior to metadata generation and so it generated the json for it, after which the matrix file was removed, creating a reference to a non-existent file.
